spring.application.name=sistema-futbol-admin

spring.datasource.url=jdbc:postgresql://localhost:5432/bd_futbol
spring.datasource.username=postgres
spring.datasource.password=admin2026**

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.format_sql=true


logging.pattern.console=[%thread] %-5level: %logger -%msg %n
logging.level.root=WARN
logging.level.com.admin.futbol.sistemafutboladmin=INFO
logging.level.org.springframework=WARN

spring.main.banner.mode=off

